### ISSUE TITLE
Friendly tips when you watch the tutorials  : )

### ISSUE THREAD

**Issue by evanhyd** [williamvietnguyen/quros#1]
#1. It is better for the pawn move generation to shift the entire pawn bitboard at once rather than individually.

#2. some of the BBC code is copied from Bluefever's chess engine code, which is NOT designed for the bitboard chess engine. Consider optimizing it using your own logic

#3. recommend you to write it in C++ 20 or above, why? You get to use lots of template meta to get compile-time optimization. You get to use C++ standard library <bit> that provides features such as std::popcount() (fastest method by using intrinsic instruction from CPU), std::rotr() or std::rotl(), which is a HUGE advantage over C. However, it is quite important to understand the algorithm behind those bitwise hacks, and I use this website for reference (http://graphics.stanford.edu/~seander/bithacks.html).  You get to use C++ standard library's multithreading, VERY VERY VERY crucial if you want to make an outstanding chess engine.

#4. don't abuse pruning too much, always test it over and over again. Higher search depth doesn't mean higher elo. Many of the time, aggressive pruning leads to a higher chance of missing finding good moves. On the other hand, lower depth doesn't mean lower elo, for example, quiescence search is really good for improving the elo.

#5. transposition table is a pain to implement, it is just too much dynamic programming.

#6. there are lots of errors in Code Monkey King's chess engine video, you probably always wanna read the comment below the videos to make sure everything is doing fine.

#7. Some good chess positions to test your engine performance: opening position, kiwipete, queen/rook/two bishop check mates

#8. Machine Learning is a scam, you wouldn't have the time and resources to build one besides copying the existed config online.

#9. Do not cheat on online chess websites with the engine, you will get IP banned along with your other smurf accounts login in the same machine && location, speaking from experience. 

#10. Make sure to turn on all the compiler optimization, SPEED SPEED SPEED

#11. Important features that boost your chess engine ELO:  alpha-beta search, move ordering, quiescence search, null move pruning, negamax searching, transposition table, multithreading, as much as possible of compile-time look up table

#12.  This project will take approximately 2-3 months.

**Comment by williamvietnguyen** [comment]
Oh thanks for the tips!

I am following a bit from BBC, but I am sort of trying to do it on my own. Example: I noticed that BBC is doing bit masking next for attack squares in a video for pawns, and then I go off on my own to try to implement it for every piece using chess programming wiki before trying to check some of my work.

I'm more familiar with C at the moment so I want to just get the hang of building a very simple working engine first using bit boards.
